name: flutter_twilio_voice
description: Provides an interface to Twilio's Programmable Voice SDK to allow adding voice-over-IP (VoIP) calling into your Flutter applications.
version: 0.0.1
repository: "https://github.com/fedeamura"
homepage: "https://github.com/fedeamura"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.dormmom.flutter_twilio_voice
        pluginClass: FlutterTwilioVoicePlugin
      ios:
        pluginClass: FlutterTwilioVoicePlugin
